### ISSUE TITLE
It usable in `kaui` for subscription?

### ISSUE THREAD

**Issue by Sigura** [killbill/killbill-dwolla-plugin#6]
Do you know the way to use it in `killbill-dwolla-plugin` for the subscription creation in `kaui`?

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for support questions. See https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md.

**Comment by Sigura** [comment]
oh, sure, thank you!
